#!/bin/bash

brew install node

# spell check
pipenv run jupyter labextension install @ijmbarr/jupyterlab_spellchecker

# matplot lib interactive
pipenv run jupyter labextension install @jupyter-widgets/jupyterlab-manager
pipenv run jupyter labextension install jupyter-matplotlib
