"""empty message

Revision ID: 3c387f97ca75
Revises: b5dc956e184e
Create Date: 2019-08-14 15:57:21.400202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c387f97ca75'
down_revision = 'b5dc956e184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'mname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('mname', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
