"""empty message

Revision ID: cadc94c9f31f
Revises: 3c387f97ca75
Create Date: 2019-08-14 15:58:53.595138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadc94c9f31f'
down_revision = '3c387f97ca75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('mname', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'mname')
    # ### end Alembic commands ###
